### ISSUE TITLE
Set up coding environment

### ISSUE THREAD

**Issue by annazwicker** [annazwicker/cat-partners#11]
Each of us needs to download Flutter and figure out which IDE we're going to use.

**Comment by annazwicker** [comment]
Starting work, going to figure out how to download Flutter and navigate Visual Studio Code.

**Comment by annazwicker** [comment]
Downloaded GitHub Desktop, Visual Studio Code, and Git.

**Comment by annazwicker** [comment]
Downloaded the Flutter SDK (this took a while), trying to run flutter doctor.  Used this link to troubleshoot why the `flutter doctor` command isn't working.  https://stackoverflow.com/questions/49343853/flutter-doctor-in-windows-power-shell-returns-error.  Used the second solution.

**Comment by annazwicker** [comment]
Had to download Visual Studio which took a while.  Needed to set this up to resolve one of the issues when I ran `flutter doctor`.  Working to further resolve the issue by downloading desktop development with C++ in Visual Studio.  This required me to download the Visual Studio Enterprise which is taking a significant amount of time.  Still not done.

**Comment by annazwicker** [comment]
The download for the Visual Studio Enterprise finally finished.  I believe my environment is mostly set up but I will confirm with teammates at Tuesday night meeting.  Stopping work here for today (a little less than 2.5 hours).

**Comment by MMSU-1987** [comment]
Start to fix issue of properly setting code environment. 
Current Issue: Attempts to load web page for Flutter on VScode are unsuccessful and output a lot of errors, despite **flutter doctor** showing google chrome is functioning with flutter

**Comment by MMSU-1987** [comment]
Currently no visible progress that it is getting better. Had attempted to uninstall and reinstall flutter to see if something different could happen.

**Comment by MMSU-1987** [comment]
Issue will likely be resolved when vector_math_64 file is fixed. Currently only shows **NULL** while other files next to it are not like that. Currently dont know how to fix it, but will find a way.

**Comment by MMSU-1987** [comment]
Fixed issue. It was the vector_math_64 file. The only reason I could think of that caused this was when I was trying to initially download flutter a few weeks ago and it got messed up when my laptop crashed(it happened a lot).

Regardless, web pages are able to load without issue. Stopping work for now(~1hr 30min, total hrs worked: 4 hrs (including meetings))

**Comment by annazwicker** [comment]
Starting work, need to figure out how to add the Android Toolchain to my environment.

**Comment by annazwicker** [comment]
Using the provided website to try and figure out why I'm still getting an error when I run flutter doctor.  https://developer.android.com/tools.  Also used this link to further figure out this problem: https://stackoverflow.com/questions/68236007/i-am-getting-error-cmdline-tools-component-is-missing-after-installing-flutter

**Comment by annazwicker** [comment]
Fixed the issues I was having with the Android toolchain.  To add cmdline tools, go to file>settings>Android SDK>SDK tools then select Android SDK Command-line Tools (latest) then apply and okay.  Close Android Studio and VS Code and then restart VS Code and run `flutter doctor`.  This fixed the error for me.  There was another command to run when I ran futter doctor `flutter doctor --android-licenses` to accept the licenses I had not approved.  This fixed all issues when I ran the regular flutter doctor command.  I believe my environment is good to go, next steps are to figure out how to run a simulator.  I'm somewhat familiar with how to do this for mobile and wearable apps but I haven't done it for a web app before.  I also want to go through some Flutter tutorials on website design versus mobile design.  Stopping work for now (1 hour).

**Comment by annazwicker** [comment]
Starting work, I noticed there is a preliminary design on Flutter and I haven't had the chance to review it yet.  I also want to double check that I can run the simulator.

**Comment by annazwicker** [comment]
Finally figured out how the navigation bar works and located the files with the different pages.  Next steps are to make my own branch and start working on the about page.

**Comment by annazwicker** [comment]
Looked at this link for creating text boxes for users to enter data in.  Also created a branch for the about page.  Next steps are to apply the information from this link (https://docs.flutter.dev/cookbook/forms/text-input) to potentially make some test text boxes.  This website was helpful in figuring out how to create a form that is submittable (https://docs.flutter.dev/cookbook/forms/validation).  Stopping work here (1 hour)
